### ISSUE TITLE
Why are you using inheritance?

### ISSUE THREAD

**Issue by Avazart** [fscdev/betterconf#10]
Why are you using inheritance?
It is bad that the base class modifies the derived.
A class decorator or a metaclass is more suitable for this task.

As an example, you could look into the dataclass module and use type annotations for better syntax, such:

```
@better_config 
class Config:
      int_var: int        # APP_INT_VAR from env
      float_var: float
      bool_var: bool
      special_var = Field("SomeSpecialNameWithoutPrefix", type=int)


config = Config(prefix="APP_")

config.int_var   # This We have a hit in IDE
```

**Comment by prostomarkeloff** [comment]
The basic design of this library uses the inheritance as an adequate pattern. As soon the library isn't developed anymore, the breaking of the compatibility is not a good idea.

**Comment by prostomarkeloff** [comment]
Okay, betterconf 4.0 now does use the decorator pattern :)
